# Generated by Django 4.2 on 2024-08-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_specification_size_gallery_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='category.jpg', upload_to='category'),
        ),
    ]
