# Generated by Django 4.2 on 2024-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_notification_user_alter_notification_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
